include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    lines_longer_than_80_chars: ignore

linter:
  rules: []

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 10
    lines-of-code: 300
    maximum-nesting: 4
    number-of-parameters: 4
  rules:
    - no-equal-then-else
    - no-boolean-literal-compare
    - avoid-nested-conditional-expressions
    - newline-before-return
  anti-patterns:
    - long-method
    - long-parameter-list
